@host = http://localhost
@port = 3000
@apiSalas = /api/salas
@apiUsuarios = /api/usuarios
@apiStaff = /api/staff

#########################
##      API salas      ##
#########################
GET {{host}}:{{port}}{{apiSalas}}
###

GET {{host}}:{{port}}{{apiSalas}}/usuario/1

###
# GET {{host}}:{{port}}{{apiSalas}}/usersala

###
POST {{host}}:{{port}}{{apiSalas}}
Content-Type: application/json

{
  "precio": "100",
  "aforo": 120,
  "nombre":"los cisnes",
  "direccion":"estanque 57",
  "descripcion": "sala bonita",
  "url_foto": "lo que sea"
}

###
PUT {{host}}:{{port}}{{apiSalas}}/editar/19
Content-Type: application/json

{
  "precio": "150",
  "disponible": true,
  "aforo": 60,
  "nombre": "Una Sala",
  "direccion": "Casa Mario, 123",
  "descripcion": "sala bonita",
  "url_foto": "lo que sea"
}

###
POST {{host}}:{{port}}{{apiSalas}}/comprobar_salas
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJleHAiOjE2ODk3NzkzMTcsImlhdCI6MTY4OTc1MDUxN30.rYxNEHb1C7H80fshmFJuAEz-iyRoFpzbHASapI0d1bA

{
  "salas_id": "1",
  "fecha_reserva": "2023-07-13",
  "hora_reserva": "08:00:00"
}

###
DELETE {{host}}:{{port}}{{apiSalas}}/20


#########################
##    API usuarios     ##
#########################
GET {{host}}:{{port}}{{apiUsuarios}}

###
GET {{host}}:{{port}}{{apiUsuarios}}/1
###
GET {{host}}:{{port}}{{apiUsuarios}}/dni/123456789-A

###
POST {{host}}:{{port}}{{apiUsuarios}}/registro
Content-Type: application/json

{
  "nombre": "pilar",
  "direccion":"Rio de Janeiro, 26",
  "email": "pili@aaruuur.com",
  "telefono":"644444444",
  "dni":"78878rugg0m",
  "username":"piliiiiiiii",
  "password":"123456"
}

###
POST {{host}}:{{port}}{{apiUsuarios}}/login
Content-Type: application/json

{
  "email": "pili@aaauuuur.com",
  "password":"123456"
}

###
PUT {{host}}:{{port}}{{apiUsuarios}}/editar/6
Content-Type: application/json

{
  "username": "lolillo2",
  "email": "pepe22@gmail.com",
  "telefono": "626626626",
  "dni": "53601579w",
  "nombre": "Er Pepe2",
  "direccion": "Calle esta app me saca de mis casillas"
}
###
DELETE {{host}}:{{port}}{{apiUsuarios}}/7

#########################
##      API staff      ##
#########################
GET {{host}}:{{port}}{{apiStaff}}

###
GET {{host}}:{{port}}{{apiStaff}}/id/3

###
GET {{host}}:{{port}}{{apiStaff}}/pedritogar

###
GET {{host}}:{{port}}{{apiStaff}}/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxLCJ1c2VyUm9sZSI6InRyYWJhamFkb3IiLCJleHAiOjE2ODk4Njg2MTcsImlhdCI6MTY4OTgzOTgxN30.BRWChjKxT5gbADWrJNgxxXB7FXolkJwGfWB0hsBd6Ec

###
POST {{host}}:{{port}}{{apiStaff}}/registro
Content-Type: application/json

{
  "nombre": "Javito",
  "rol":"trabajador",
  "usuario": "javito2",
  "password":"654987",
  "email":"javito@agosto.com"
}

###
POST {{host}}:{{port}}{{apiStaff}}/login
Content-Type: application/json

{
  "email":"javito@agosto.com",
  "password":"654987"
}

###
PUT {{host}}:{{port}}{{apiStaff}}/editar/21
Content-Type: application/json

{
  "nombre": "anananana",
  "rol": "trabajador",
  "usuario": "anaita",
  "nombre": "La Ana",
  "email": "asdfasdfasdfasdf@ana.com"
}

###
DELETE {{host}}:{{port}}{{apiStaff}}/22
