@host = http://localhost
@port = 3000
@apiSalas = /api/salas
@apiUsuarios = /api/usuarios
@apiStaff = /api/staff

#########################
##      API salas      ##
#########################

GET {{host}}:{{port}}{{apiSalas}}/reservadas
###
GET {{host}}:{{port}}{{apiSalas}}/libres

###

GET {{host}}:{{port}}{{apiSalas}}/usuario/3

###
GET {{host}}:{{port}}{{apiSalas}}/usersala

###
DELETE {{host}}:{{port}}{{apiSalas}}/5

#########################
##    API usuarios     ##
#########################

GET {{host}}:{{port}}{{apiUsuarios}}/usuario/3

###

GET {{host}}:{{port}}{{apiUsuarios}}/987654321-B

###
DELETE {{host}}:{{port}}{{apiUsuarios}}/2

#########################
##      API staff      ##
#########################

GET {{host}}:{{port}}{{apiStaff}}/2

###

GET {{host}}:{{port}}{{apiStaff}}/staff/pedritogar

###
DELETE {{host}}:{{port}}{{apiStaff}}/2
